//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KO.Recursos.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso total.
        /// </summary>
        public static string AccesoTotal {
            get {
                return ResourceManager.GetString("AccesoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string Acciones {
            get {
                return ResourceManager.GetString("Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        public static string Activa {
            get {
                return ResourceManager.GetString("Activa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar.
        /// </summary>
        public static string Activar {
            get {
                return ResourceManager.GetString("Activar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuales.
        /// </summary>
        public static string Actuales {
            get {
                return ResourceManager.GetString("Actuales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración.
        /// </summary>
        public static string Administracion {
            get {
                return ResourceManager.GetString("Administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Comentarios.
        /// </summary>
        public static string AgregarComentarios {
            get {
                return ResourceManager.GetString("AgregarComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Médico.
        /// </summary>
        public static string AgregarMedico {
            get {
                return ResourceManager.GetString("AgregarMedico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Paciente.
        /// </summary>
        public static string AgregarPaciente {
            get {
                return ResourceManager.GetString("AgregarPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Vacuna.
        /// </summary>
        public static string AgregarVacuna {
            get {
                return ResourceManager.GetString("AgregarVacuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicaciones.
        /// </summary>
        public static string Aplicaciones {
            get {
                return ResourceManager.GetString("Aplicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar Filtros.
        /// </summary>
        public static string AplicarFiltros {
            get {
                return ResourceManager.GetString("AplicarFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calidad.
        /// </summary>
        public static string Calidad {
            get {
                return ResourceManager.GetString("Calidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Estado.
        /// </summary>
        public static string CambiarEstado {
            get {
                return ResourceManager.GetString("CambiarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando.
        /// </summary>
        public static string Cargando {
            get {
                return ResourceManager.GetString("Cargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        public static string Cargar {
            get {
                return ResourceManager.GetString("Cargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrada.
        /// </summary>
        public static string Cerrada {
            get {
                return ResourceManager.GetString("Cerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        public static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click acá para ingresar.
        /// </summary>
        public static string ClickIngresar {
            get {
                return ResourceManager.GetString("ClickIngresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colapsar.
        /// </summary>
        public static string Colapsar {
            get {
                return ResourceManager.GetString("Colapsar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string Comentario {
            get {
                return ResourceManager.GetString("Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string Comentarios {
            get {
                return ResourceManager.GetString("Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Cambio.
        /// </summary>
        public static string ConfirmarCambio {
            get {
                return ResourceManager.GetString("ConfirmarCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        public static string ConfirmarPassword {
            get {
                return ResourceManager.GetString("ConfirmarPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta.
        /// </summary>
        public static string Consulta {
            get {
                return ResourceManager.GetString("Consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string Continuar {
            get {
                return ResourceManager.GetString("Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Generales.
        /// </summary>
        public static string DatosGenerales {
            get {
                return ResourceManager.GetString("DatosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Detalle {
            get {
                return ResourceManager.GetString("Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error en nuestros servicios, por favor comuníquese con el área de sistemas..
        /// </summary>
        public static string ErrorGenerico {
            get {
                return ResourceManager.GetString("ErrorGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estados.
        /// </summary>
        public static string Estados {
            get {
                return ResourceManager.GetString("Estados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expandir.
        /// </summary>
        public static string Expandir {
            get {
                return ResourceManager.GetString("Expandir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar.
        /// </summary>
        public static string Exportar {
            get {
                return ResourceManager.GetString("Exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar a Excel.
        /// </summary>
        public static string ExportarExcel {
            get {
                return ResourceManager.GetString("ExportarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Cambio.
        /// </summary>
        public static string FechaCambio {
            get {
                return ResourceManager.GetString("FechaCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desde.
        /// </summary>
        public static string FechaDesde {
            get {
                return ResourceManager.GetString("FechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Hasta.
        /// </summary>
        public static string FechaHasta {
            get {
                return ResourceManager.GetString("FechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Nacimiento.
        /// </summary>
        public static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filas por página.
        /// </summary>
        public static string FilasPorPagina {
            get {
                return ResourceManager.GetString("FilasPorPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        public static string Filtrar {
            get {
                return ResourceManager.GetString("Filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        public static string Filtros {
            get {
                return ResourceManager.GetString("Filtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin fechas especificadas.
        /// </summary>
        public static string FiltroSinFecha {
            get {
                return ResourceManager.GetString("FiltroSinFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD/MM/AAAA.
        /// </summary>
        public static string Formato {
            get {
                return ResourceManager.GetString("Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionalidad.
        /// </summary>
        public static string Funcionalidad {
            get {
                return ResourceManager.GetString("Funcionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionalidades.
        /// </summary>
        public static string Funcionalidades {
            get {
                return ResourceManager.GetString("Funcionalidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactiva.
        /// </summary>
        public static string Inactiva {
            get {
                return ResourceManager.GetString("Inactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivar.
        /// </summary>
        public static string Inactivar {
            get {
                return ResourceManager.GetString("Inactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string Inactivo {
            get {
                return ResourceManager.GetString("Inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros.
        /// </summary>
        public static string LabelNoCoincidences {
            get {
                return ResourceManager.GetString("LabelNoCoincidences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string Limpiar {
            get {
                return ResourceManager.GetString("Limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar Filtros.
        /// </summary>
        public static string LimpiarFiltros {
            get {
                return ResourceManager.GetString("LimpiarFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado.
        /// </summary>
        public static string Listado {
            get {
                return ResourceManager.GetString("Listado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string Marca {
            get {
                return ResourceManager.GetString("Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula.
        /// </summary>
        public static string Matricula {
            get {
                return ResourceManager.GetString("Matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Médico.
        /// </summary>
        public static string Medico {
            get {
                return ResourceManager.GetString("Medico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Médicos.
        /// </summary>
        public static string Medicos {
            get {
                return ResourceManager.GetString("Medicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea ACTIVAR?.
        /// </summary>
        public static string MensajeActivar {
            get {
                return ResourceManager.GetString("MensajeActivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea ACTIVAR la vacuna?.
        /// </summary>
        public static string MensajeActivarVacuna {
            get {
                return ResourceManager.GetString("MensajeActivarVacuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique usuario y contraseña.
        /// </summary>
        public static string MensajeCredencialesInvalidas {
            get {
                return ResourceManager.GetString("MensajeCredencialesInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Activados correctamente.
        /// </summary>
        public static string MensajeDatosActivadosOk {
            get {
                return ResourceManager.GetString("MensajeDatosActivadosOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Actualizados correctamente.
        /// </summary>
        public static string MensajeDatosActualizadosOk {
            get {
                return ResourceManager.GetString("MensajeDatosActualizadosOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Guardados correctamente.
        /// </summary>
        public static string MensajeDatosGuardadosOk {
            get {
                return ResourceManager.GetString("MensajeDatosGuardadosOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Inactivados correctamente.
        /// </summary>
        public static string MensajeDatosInactivadosOk {
            get {
                return ResourceManager.GetString("MensajeDatosInactivadosOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea INACTIVAR?.
        /// </summary>
        public static string MensajeInactivar {
            get {
                return ResourceManager.GetString("MensajeInactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea INACTIVAR la vacuna?.
        /// </summary>
        public static string MensajeInactivarVacuna {
            get {
                return ResourceManager.GetString("MensajeInactivarVacuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no se encuentra autorizado para ver esta página.
        /// </summary>
        public static string MensajeNoAutorizado {
            get {
                return ResourceManager.GetString("MensajeNoAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña ingresada es incorrecta.
        /// </summary>
        public static string MensajePasswordInvalida {
            get {
                return ResourceManager.GetString("MensajePasswordInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva.
        /// </summary>
        public static string Nueva {
            get {
                return ResourceManager.GetString("Nueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevos.
        /// </summary>
        public static string Nuevos {
            get {
                return ResourceManager.GetString("Nuevos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número O. Social.
        /// </summary>
        public static string NumeroObraSocial {
            get {
                return ResourceManager.GetString("NumeroObraSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obra Social.
        /// </summary>
        public static string ObraSocial {
            get {
                return ResourceManager.GetString("ObraSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo Médicos.
        /// </summary>
        public static string ObteniendoMedicos {
            get {
                return ResourceManager.GetString("ObteniendoMedicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo Pacientes.
        /// </summary>
        public static string ObteniendoPacientes {
            get {
                return ResourceManager.GetString("ObteniendoPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo Vacunas.
        /// </summary>
        public static string ObteniendoVacunas {
            get {
                return ResourceManager.GetString("ObteniendoVacunas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operador.
        /// </summary>
        public static string Operador {
            get {
                return ResourceManager.GetString("Operador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        public static string Paciente {
            get {
                return ResourceManager.GetString("Paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacientes.
        /// </summary>
        public static string Pacientes {
            get {
                return ResourceManager.GetString("Pacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente.
        /// </summary>
        public static string Pendiente {
            get {
                return ResourceManager.GetString("Pendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por.
        /// </summary>
        public static string Por {
            get {
                return ResourceManager.GetString("Por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor revise los datos ingresados.
        /// </summary>
        public static string PorFavorRevise {
            get {
                return ResourceManager.GetString("PorFavorRevise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro eliminado.
        /// </summary>
        public static string RegistroEliminado {
            get {
                return ResourceManager.GetString("RegistroEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        public static string Reportes {
            get {
                return ResourceManager.GetString("Reportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione....
        /// </summary>
        public static string Seleccione {
            get {
                return ResourceManager.GetString("Seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Rol.
        /// </summary>
        public static string SeleccioneRol {
            get {
                return ResourceManager.GetString("SeleccioneRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Tipo de Acceso.
        /// </summary>
        public static string SeleccioneTipoAcceso {
            get {
                return ResourceManager.GetString("SeleccioneTipoAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin datos.
        /// </summary>
        public static string SinDatos {
            get {
                return ResourceManager.GetString("SinDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros.
        /// </summary>
        public static string SinRegistros {
            get {
                return ResourceManager.GetString("SinRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo permite sólo números y guiones.
        /// </summary>
        public static string SoloNumerosYGuiones {
            get {
                return ResourceManager.GetString("SoloNumerosYGuiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Acceso.
        /// </summary>
        public static string TipoAcceso {
            get {
                return ResourceManager.GetString("TipoAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacunatorio.
        /// </summary>
        public static string TituloVacunatorio {
            get {
                return ResourceManager.GetString("TituloVacunatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas.
        /// </summary>
        public static string Todas {
            get {
                return ResourceManager.GetString("Todas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuna.
        /// </summary>
        public static string Vacuna {
            get {
                return ResourceManager.GetString("Vacuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacunaciones.
        /// </summary>
        public static string Vacunaciones {
            get {
                return ResourceManager.GetString("Vacunaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacunas.
        /// </summary>
        public static string Vacunas {
            get {
                return ResourceManager.GetString("Vacunas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacunatorio.
        /// </summary>
        public static string Vacunatorio {
            get {
                return ResourceManager.GetString("Vacunatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha olvidado ingresar su Nombre.
        /// </summary>
        public static string ValidacionCampoNombreRequerido {
            get {
                return ResourceManager.GetString("ValidacionCampoNombreRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha olvidado ingresar su Contraseña.
        /// </summary>
        public static string ValidacionCampoPasswordRequerido {
            get {
                return ResourceManager.GetString("ValidacionCampoPasswordRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha olvidado ingresar su Usuario.
        /// </summary>
        public static string ValidacionCampoUsuarioRequerido {
            get {
                return ResourceManager.GetString("ValidacionCampoUsuarioRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string Ver {
            get {
                return ResourceManager.GetString("Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Detalle.
        /// </summary>
        public static string VerDetalle {
            get {
                return ResourceManager.GetString("VerDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver al inicio.
        /// </summary>
        public static string VolverAInicio {
            get {
                return ResourceManager.GetString("VolverAInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver al listado.
        /// </summary>
        public static string VolverAlListado {
            get {
                return ResourceManager.GetString("VolverAlListado", resourceCulture);
            }
        }
    }
}
