//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KO.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Acceso.
        /// </summary>
        public static string AccessType {
            get {
                return ResourceManager.GetString("AccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        public static string ActiveFem {
            get {
                return ResourceManager.GetString("ActiveFem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string ActiveMasc {
            get {
                return ResourceManager.GetString("ActiveMasc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Comentarios.
        /// </summary>
        public static string AddComments {
            get {
                return ResourceManager.GetString("AddComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hacer Pedido.
        /// </summary>
        public static string AddOrder {
            get {
                return ResourceManager.GetString("AddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Mesa.
        /// </summary>
        public static string AddTable {
            get {
                return ResourceManager.GetString("AddTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Usuario.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas.
        /// </summary>
        public static string AllFemenine {
            get {
                return ResourceManager.GetString("AllFemenine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string AllMasculine {
            get {
                return ResourceManager.GetString("AllMasculine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedir la cuenta.
        /// </summary>
        public static string AskBill {
            get {
                return ResourceManager.GetString("AskBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebida.
        /// </summary>
        public static string Bebida {
            get {
                return ResourceManager.GetString("Bebida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebidas.
        /// </summary>
        public static string Bebidas {
            get {
                return ResourceManager.GetString("Bebidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llamar al camarero.
        /// </summary>
        public static string CallWaiter {
            get {
                return ResourceManager.GetString("CallWaiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camarero.
        /// </summary>
        public static string Camarero {
            get {
                return ResourceManager.GetString("Camarero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        public static string Cargar {
            get {
                return ResourceManager.GetString("Cargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Estado.
        /// </summary>
        public static string ChangeState {
            get {
                return ResourceManager.GetString("ChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar Filtros.
        /// </summary>
        public static string CleanFilters {
            get {
                return ResourceManager.GetString("CleanFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click acá para ingresar.
        /// </summary>
        public static string ClickEnter {
            get {
                return ResourceManager.GetString("ClickEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrada.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        public static string CloseSession {
            get {
                return ResourceManager.GetString("CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colapsar.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuraciones.
        /// </summary>
        public static string Configurations {
            get {
                return ResourceManager.GetString("Configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creado por Karina Orofino.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuales.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desde.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Hasta.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir Bebidas.
        /// </summary>
        public static string ElegirBebidas {
            get {
                return ResourceManager.GetString("ElegirBebidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir Mesa.
        /// </summary>
        public static string ElegirMesa {
            get {
                return ResourceManager.GetString("ElegirMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entradas.
        /// </summary>
        public static string Entradas {
            get {
                return ResourceManager.GetString("Entradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expandir.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar a Excel.
        /// </summary>
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        public static string Filtrar {
            get {
                return ResourceManager.GetString("Filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        public static string Filtros {
            get {
                return ResourceManager.GetString("Filtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD/MM/AAAA.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error en nuestros servicios, por favor comuníquese con el área de sistemas..
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir al Menú.
        /// </summary>
        public static string GoToMenu {
            get {
                return ResourceManager.GetString("GoToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarniciones.
        /// </summary>
        public static string Guarniciones {
            get {
                return ResourceManager.GetString("Guarniciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivar.
        /// </summary>
        public static string Inactivate {
            get {
                return ResourceManager.GetString("Inactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactiva.
        /// </summary>
        public static string InactiveFem {
            get {
                return ResourceManager.GetString("InactiveFem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string InactiveMasc {
            get {
                return ResourceManager.GetString("InactiveMasc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo Menu.
        /// </summary>
        public static string LoadingMenuItems {
            get {
                return ResourceManager.GetString("LoadingMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo Pedidos.
        /// </summary>
        public static string LoadingOrders {
            get {
                return ResourceManager.GetString("LoadingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo Mesas.
        /// </summary>
        public static string LoadingTables {
            get {
                return ResourceManager.GetString("LoadingTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutas.
        /// </summary>
        public static string Minutas {
            get {
                return ResourceManager.GetString("Minutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea ACTIVAR?.
        /// </summary>
        public static string MsgActivate {
            get {
                return ResourceManager.GetString("MsgActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Activados correctamente.
        /// </summary>
        public static string MsgActivationOk {
            get {
                return ResourceManager.GetString("MsgActivationOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Guardados correctamente.
        /// </summary>
        public static string MsgCreationOk {
            get {
                return ResourceManager.GetString("MsgCreationOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea eliminar la aplicación?.
        /// </summary>
        public static string MsgDeleteOk {
            get {
                return ResourceManager.GetString("MsgDeleteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea INACTIVAR?.
        /// </summary>
        public static string MsgInactivate {
            get {
                return ResourceManager.GetString("MsgInactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Inactivados correctamente.
        /// </summary>
        public static string MsgInactivationOk {
            get {
                return ResourceManager.GetString("MsgInactivationOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña ingresada es incorrecta.
        /// </summary>
        public static string MsgIncorrectPassword {
            get {
                return ResourceManager.GetString("MsgIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique usuario y contraseña.
        /// </summary>
        public static string MsgInvalidCredentials {
            get {
                return ResourceManager.GetString("MsgInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es un usuario registrado. Comuníquese con el administrador para que lo registre..
        /// </summary>
        public static string MsgNotAUser {
            get {
                return ResourceManager.GetString("MsgNotAUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Actualizados correctamente.
        /// </summary>
        public static string MsgUpdateOk {
            get {
                return ResourceManager.GetString("MsgUpdateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva.
        /// </summary>
        public static string NewFem {
            get {
                return ResourceManager.GetString("NewFem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string NewMasc {
            get {
                return ResourceManager.GetString("NewMasc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevos.
        /// </summary>
        public static string NewPlural {
            get {
                return ResourceManager.GetString("NewPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no se encuentra autorizado para ver esta página.
        /// </summary>
        public static string NotAuthorize {
            get {
                return ResourceManager.GetString("NotAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo Bebidas.
        /// </summary>
        public static string ObteniendoBebidas {
            get {
                return ResourceManager.GetString("ObteniendoBebidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo permite sólo números y guiones.
        /// </summary>
        public static string OnlyNumbersAndDashes {
            get {
                return ResourceManager.GetString("OnlyNumbersAndDashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastas / Salsas.
        /// </summary>
        public static string Pastas {
            get {
                return ResourceManager.GetString("Pastas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platos Elaborados.
        /// </summary>
        public static string PlatosElaborados {
            get {
                return ResourceManager.GetString("PlatosElaborados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor revise los datos ingresados.
        /// </summary>
        public static string PleaseReview {
            get {
                return ResourceManager.GetString("PleaseReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postres.
        /// </summary>
        public static string Postres {
            get {
                return ResourceManager.GetString("Postres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karen Finegold Productions.
        /// </summary>
        public static string ProducedBy {
            get {
                return ResourceManager.GetString("ProducedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filas por página.
        /// </summary>
        public static string RowsPerPage {
            get {
                return ResourceManager.GetString("RowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salsa.
        /// </summary>
        public static string Salsa {
            get {
                return ResourceManager.GetString("Salsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string See {
            get {
                return ResourceManager.GetString("See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string SeeDetail {
            get {
                return ResourceManager.GetString("SeeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Pedido.
        /// </summary>
        public static string SeeOrder {
            get {
                return ResourceManager.GetString("SeeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesa.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesas.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Resto.
        /// </summary>
        public static string TitleSelfResto {
            get {
                return ResourceManager.GetString("TitleSelfResto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto Total.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Unitario.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha olvidado ingresar su Nombre.
        /// </summary>
        public static string ValNameRequired {
            get {
                return ResourceManager.GetString("ValNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha olvidado ingresar su Contraseña.
        /// </summary>
        public static string ValPasswordRequired {
            get {
                return ResourceManager.GetString("ValPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozo.
        /// </summary>
        public static string Waiter {
            get {
                return ResourceManager.GetString("Waiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozo Back Up.
        /// </summary>
        public static string WaiterBackUp {
            get {
                return ResourceManager.GetString("WaiterBackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
